# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors
Tensor means vector.

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
world = tf.constant(' World')

In [7]:
result = hello + world

In [8]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [20]:
result

b'Hello World'

## Computations

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(tensor_1 + tensor_2)
result

3

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
with tf.Session() as sess:
    result = sess.run(fill_mat)
print(result)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [26]:
myzeros = tf.zeros((4,4))
print(myzeros)

Tensor("zeros_3:0", shape=(4, 4), dtype=float32)


In [27]:
myones = tf.ones((4,4))
print(myones)

Tensor("ones_1:0", shape=(4, 4), dtype=float32)


In [28]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
print(myrandn)

Tensor("random_normal_1:0", shape=(4, 4), dtype=float32)


In [29]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)
print(myrandu)

Tensor("random_uniform_1:0", shape=(4, 4), dtype=float32)


In [30]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]
print(my_ops)

[<tf.Tensor 'Const_4:0' shape=() dtype=int32>, <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>, <tf.Tensor 'zeros_3:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'ones_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_normal_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>]


## Interactive Session

Useful for Notebook Sessions

In [32]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [33]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.08911982  0.3129446   0.19234432  0.4658083 ]
 [-0.66653645 -0.35466677  0.38390362 -0.05206274]
 [-0.40131718  0.02615953  0.03541684 -0.5788311 ]
 [-0.43288812  0.0244923   0.05884625  0.23140113]]


[[0.82177794 0.13546145 0.3224491  0.8799814 ]
 [0.94127345 0.8278401  0.11362112 0.79106927]
 [0.06701112 0.81288064 0.56227756 0.16688251]
 [0.96021414 0.96349025 0.12517047 0.19781256]]




## Matrix Multiplication

In [46]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [47]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [48]:
b = tf.constant([[10],[100]])

In [49]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [50]:
result = tf.matmul(a,b)

In [51]:
result.eval()

array([[210],
       [430]], dtype=int32)